### ISSUE TITLE
Some syntax causes broken highlight.

### ISSUE THREAD

**Issue by iFwu** [xekri/vscode-styled-jsx#4]
![70ceb97e-e127-4824-a688-e2ebf3ef6055](https://user-images.githubusercontent.com/16523864/33882777-477183e0-df74-11e7-9d8a-8f673754d438.jpg)

**Comment by victordidenko** [comment]
+1 same for me

**Comment by kennedyrose** [comment]
Same here. I think it's the `|css` in [this line](https://github.com/iFwu/vscode-styled-jsx/blob/master/syntaxes/jsx-styled.json#L12) but I don't know how to test VS extensions.

**Comment by athrunsun** [comment]
@kennedyrose That's the same reason why this extension doesn't work with TypeScript, where we write styled jsx like this:

```typescript
<style jsx={true}>{...}</style>
```

CC: @iFwu

**Comment by iFwu** [comment]
fixed

**Comment by readeral** [comment]
Still experiencing this issue ("css`" causing all following code to be unhighlighted) with v1.0.0 installed in vs code on macOS Mojave. Have confirmed the version by running 'code --list-extensions --show-versions" in terminal, and it reports back "vscode-styled-jsx@1.0.0"

Example screenshot attached

<img width="728" alt="screen shot 2018-10-22 at 9 06 59 pm" src="https://user-images.githubusercontent.com/15904136/47287570-725fd680-d63e-11e8-85c7-672deed8c908.png">

**Comment by readeral** [comment]
Thanks iFwu. Anything I can do to help let me know, but haven’t had a chance to dig into the source to determine the issue, sorry!

**Comment by iFwu** [comment]
@readeral The `` css`flex: 1;` `` doesn't match the [external styles](https://github.com/zeit/styled-jsx#external-styles) rule in the `styled-jsx`. That's why the syntax highlight is broken.

Is the css here use styled-components? I see the syntax of styled-components is something like this.
Maybe you can disable the extension in the workspace that use styled-components syntax.

**Comment by readeral** [comment]
No not using styled-components, using Emotion.sh

**Comment by karlhorky** [comment]
Confirmed that this extension breaks [`vscode-styled-components`](https://github.com/styled-components/vscode-styled-components) with Emotion and styled-components code.

This only started happening for me on the May 2020 version of VS Code (version 1.46).

![Kapture 2020-06-19 at 14 50 36](https://user-images.githubusercontent.com/1935696/85134376-a8eb5b80-b23c-11ea-8794-32c66ce30b78.gif)

See also:

- https://github.com/emotion-js/emotion/issues/1316#issuecomment-486122598
- https://github.com/styled-components/vscode-styled-components/issues/208#issuecomment-646606763

**Comment by tettoffensive** [comment]
@karlhorky This is happening to me as well. I just disabled `vscode-styled-jsx` for now, since I'm mainly using emotion and twin.macro (for tailwind)
